### ISSUE TITLE
URGENT: Tiny Components

### ISSUE THREAD

**Issue by AdinAck** [ECE-196/pcbassignment-team-4#1]
Hi Team 4,

You accidentally used `0201` components when I think you intended to use `0603` components.

These are so small you will not be able to place them.

Please update your PCB as fast as you can. I will know to look again when you resolve this issue.

**Comment by CesarT0rres** [comment]
Thank you for letting us know, I have made the changes and will be updating the export file in a couple of minutes

**Comment by CesarT0rres** [comment]
Repository has been updated. Please let us know if any other changes need to be made, thank you!

**Comment by AdinAck** [comment]
Thanks!
